# Generated by Django 3.0.6 on 2020-05-30 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='memo1',
            new_name='memo',
        ),
        migrations.RenameField(
            model_name='todo',
            old_name='title1',
            new_name='title',
        ),
    ]
